In [ ]:
# class 정의, class 생성
# class 클래스명:
# 클래스명() -> 생성자 -> instance (객체)
class Aclass:
    def __init__(self, num1, num2): # class 안의 함수 == 매서드
        self.num1 = num1
        self.num2 = num2
        print("class 생성")
        
    def __del__(self): # 프로그램 종료 시 자동으로 실행
        print("class 소멸")

    def get_sum(self):
        print("class 내부 함수 실행")
        return self.num1 + self.num2
    
a = Aclass(10, 20) # 생성자 => class 내부의 __init__ 함수가 실행
print(a.num1, a.num2, a.get_sum()) 
print()
b = Aclass(30, 40)
print(b.num1, b.num2) # init 말고 다른 함수는 수행 안 됨

a_list = [a, b]
print()
print(a_list[0].num1 + a_list[1].num2)

class Student:
    def __init__(self, name, korean, math, english, science):
        self.name = name
        self.korean = korean
        self.math = math
        self.english = english
        self.science = science
        
    def get_sum(self):
        return self.korean + self.math + self.english + self.science
    def get_avg(self):
        return self.get_sum()/4
    def to_string(self):
        return "{}\t{}\t{}\t{}\t{}\t{}\t{}".format(self.name, self.get_sum(), self.get_avg(), self.korean, self.math, 
                                                   self.english, self.science)
        
students_class = [
    Student("윤인성", 87, 98, 88, 95),
    Student("연하진", 92, 98, 96, 98),
    Student("구지연", 76, 96, 94, 90),
    Student("나선주", 98, 92, 96, 92),
    Student("윤아린", 95, 98, 98, 98),
    Student("윤명월", 64, 88, 92, 92)
]

In [ ]:
class Student:
    def __init__(self, name, korean, math, english, science):
        self.name = name
        self.korean = korean
        self.math = math
        self.english = english
        self.science = science
    
    def file_write(self):
        fp.write(self.name + "," + str(self.kor) + "," + str(self.english) + "\n")
        
    def input_data():
        name = input("이름 :")
        if name == "q":
            return "q"
        while True:
            score = input("국어, 영어, 점수 입력 : (50 40)".split())
            if len(score) == 2:
                break
        student = Student(name, int(score[0]), int(score[1]))
        student.file_write()
        return
    
def search_data():
    fe.seek(0)
    s_name = input("검색할 이름 : ")
    for line in fp:
        line_data = line.split(",")
        if s_name == line_data[0]:
            return line_data
        return
    
fp = open("class_flie.txt" "r")

try:
    while True:
        name = input("이름 :")
        if name == "q":
            break
        score = int(input("점수 입력 : "))
        student = Student(name, score)
        student.file_write()
        
        data = search_data()
        if data:
            print("{} : {}, {}".format(data[0], data[1], data[2]))
        else:
            print("검색할 자료 없음")
            
except Exception as e:
    print("error", e)
finally:
    fp.close()

In [ ]:
# 학생 클래스를 선언합니다.
class Student:
    def study(self):
        print("공부를 합니다.")

# 선생님 클래스를 선언합니다.
class Teacher:
    def teach(self):
        print("학생을 가르칩니다.")

# 교실 내부의 객체 리스트를 생성합니다.
classroom = [Student(), Student(), Teacher(), Student(), Student()]

# 반복을 적용해서 적절한 함수를 호출하게 합니다.
for person in classroom:
    if isinstance(person, Student):
        person.study()
    elif isinstance(person, Teacher):
        person.teach()

In [ ]:
class Student:
    def __init__(self, name, korean, math, english, science):
        self.name = name
        self.korean = korean
        self.math = math
        self.english = english
        self.science = science
        
    def get_sum(self):
        return self.korean + self.math + self.english + self.science
    def get_avg(self):
        return self.get_sum()/4
#    def to_string(self):
    def __str__(self, student):
        return "{}\t{}\t{}\t{}\t{}\t{}\t{}".format(self.name, self.get_sum(), self.get_avg(), self.korean, self.math, 
                                                   self.english, self.science)

In [ ]:
students = [
    Student("윤인성", 87, 98, 88, 95),
    Student("연하진", 92, 98, 96, 98),
    Student("구지연", 76, 96, 94, 90),
    Student("나선주", 98, 92, 96, 92),
    Student("윤아린", 95, 98, 98, 98),
    Student("윤명월", 64, 88, 92, 92)
]

In [ ]:
for student in students:
    print(str(student)

In [ ]:
class Stu:
    count = 0
    
    def __init__(self, name, score):
        self.name = name
        self.score = score
        
        Stu.count += 1
        print("{} 번째 입력".format(Stu.count))

In [ ]:
stu_list = [Stu("a", 90), Stu("b", 80)]
print(Stu.count)

In [ ]:
# 이름, 성적을 입력받아 Student 클래스에 instance에 저장하는데 이 부분을 리스트로
# 이름에 q 입력되면 입력 종료
# 입력된 숫자만큼 데이터 출력
class Student:
    count = 0
    
    def __init__(self, name, score):
        self.name = name
        self.score = score
        
        Student.count += 1
        
students = []
while True:
    name = input("이름: ")
    if name == "q":
        break

    score = int(input("점수: "))
    students.append(Student(name, score))

print("입력한 총 개수 : {}".format(Student.count))

for i in range(Student.count):
    print(students[i].name, students[i].score)

In [ ]:
# 모듈을 가져옵니다.
import math

# 클래스를 선언합니다.
class Circle:
    def __init__(self, radius):
        self.__radius = radius # __변수명 : privite 변수
    def get_circumference(self):
        return 2 * math.pi * self.__radius
    def get_area(self):
        return math.pi * (self.__radius ** 2)
    
    def get_radius(self):
        return self.__radius
    def set_radius(self, value):
        self.__radius = value

# 원의 둘레와 넓이를 구합니다.
circle = Circle(10)
print("원의 둘레:", circle.get_circumference())
print("원의 넓이:", circle.get_area())
print(circle.get_radius())
circle.set_radius(20)
print(circle.get_radius())

In [ ]:
# 상속
class Parent:
    def __init__(self):
        self.value = "테스트"
        print("Parent 클래스의 __init()__ 메서드가 호출되었습니다.")
    def test(self):
        print("Parent 클래스의 test() 메서드입니다.")

# 자식 클래스를 선언합니다.
class Child(Parent):
    def __init__(self):
        Parent.__init__(self) 
        print("Child 클래스의 __init()__ 메서드가 호출되었습니다.")

# 자식 클래스의 인스턴스를 생성하고 부모의 메서드를 호출합니다.
child = Child()
child.test()
print(child.value)

In [1]:
# numpy : 배열의 연산등을 쉽게 처리하는 모듈
# reshape
import numpy as np

In [52]:
a = np.arange(15).reshape(3,5)
print(a, type(a))
print(a.ndim, a.shape, a.size, a.dtype.name, a.dtype.itemsize)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] <class 'numpy.ndarray'>
2 (3, 5) 15 int32 4


In [ ]:
np.arange(-10, 5, 0.5)

In [53]:
np.arange(-10, 5, 0.5).reshape(5, 6)

array([[-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5],
       [ -7. ,  -6.5,  -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5,  -2. ,  -1.5],
       [ -1. ,  -0.5,   0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5,   4. ,   4.5]])

In [ ]:
a_list = [1, 2, 3, 4, 5, 6]
a_array = np.array(a_list)
print(type(a_list), type(a_array), a_list, a_array)

In [ ]:
# inf, Nan 초기값 설정한 배열 생성
a = np.zeros(5)
b = np.zeros((2, 3))
c = np.zeros((5, 2), dtype = "i")
d = np.zeros(5, dtype = "U4")
e = np.ones((2, 3, 4), dtype = "i8")
f = np.ones_like(b, dtype = "f")
g = ()
g = np.empty((4, 3)) # 초기화 되어있지 않아 쓰레기 값이 들어가 있음

print(a)
print(b)
print(c)
print(d)
print(e)
print(f)
print(g)

In [ ]:
z2 = np.array([[5.0],[10.0],[15.0]])
print(z2)

In [ ]:
# array 연산
x1 = np.array([1, 2, 3, 4])
y1 = np.array([4, 5, 6, 8])
x2 = np.array([[1, 2], [3, 4]])
z1 = np.array([-1, -2])
z2 = np.array([[1, 2, 3, 4], [4, 5, 6, 8]])

print(x1 + y1)
print(x2 + z1)
print(x2.flatten())
print(x1.reshape(2, 2))
print(z2.reshape(2, 2, 2))

In [ ]:
# indexing, slicing, iterating
a = np.arange(10) ** 2
print(a)
print(a[2]) # 0 index 부터 시작, 4
print(a[3:5]) # 시작은 포함, 끝은 미포함
print(a[0:6:2]) # [start : end : step]
a[0:6:2] = -a[0:6:2]
print(a[0:6:2])
print(a[::-1])

b = a.reshape(2, 5)
print(b)
print(b[:,1]) # [1, 36], 모든행, 1열
print(b[-1,-1]) # 81

In [ ]:
a = np.array([[2, 3, 4], [5, 6, 2], [9, 6, 7]])
print(np.argmax(a, axis = 1)) # axis = 0 행, axis = 1 열 / arg = index

In [ ]:
print(np.mean(a), np.var(a), np.median(a), len(a), a.size)

In [ ]:
np.random.seed(0)
np.random.rand(5)

In [ ]:
np.random.choice(5, 3, replace = False)

In [ ]:
# np.random.seed(0)
np.random.randint(10, 20, size = 10)
np.random.randint(10, 20, size = (2,5))

In [15]:
x = np.arange(20 + 1)
print(x)
print(x[x % 3 == 0])
print(x[x % 4 == 1])
print(x[(x % 3 == 0) & (x % 4 == 1)]) # &, |

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 0  3  6  9 12 15 18]
[ 1  5  9 13 17]
[9]


In [58]:
# 1부터 100까지의 수중에서 3의 배수만 배열로 생성
x = np.arange(1, 100 + 1)
x = x[x % 3 == 0]
print(x)

# 위에서 생성된 배열의 값 중에서 임의로 5개의 값을 출력
y = np.random.choice(x, 5)
print(y)

# 위의 배열의 사이즈를 확인한 후 행이 3인 2차원 배열을 생성
print()
print(x.reshape(3, int(x.size / 3)))
# 배열의 원소중에서 5의 배수만 출력
print()
print(z[z % 5 == 0])

[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72
 75 78 81 84 87 90 93 96 99]
[72 42 69 54 99]

[[ 3  6  9 12 15 18 21 24 27 30 33]
 [36 39 42 45 48 51 54 57 60 63 66]
 [69 72 75 78 81 84 87 90 93 96 99]]

[15 30 45 60 75 90]
